"""renombrar tabla categorias y creacion de tablas hijas

Revision ID: b8b52a7ca498
Revises: 7adeb2dab83c
Create Date: 2026-09-25 20:42:13.272256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b52a7ca498'
down_revision = '7adeb2dab83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('categoria', 'categorias'
    )
    op.create_table('libros_escritores',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('escritor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escritor_id'], ['escritores.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'escritor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('categorias', 'categoria')
    op.drop_table('libros_escritores')
    # ### end Alembic commands ###
