"""creacion tabla prestamos y ejemplares

Revision ID: bed1ebfb72b5
Revises: b8b52a7ca498
Create Date: 2026-09-25 20:55:54.748683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed1ebfb72b5'
down_revision = 'b8b52a7ca498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejemplares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_inventario', sa.VARCHAR(length=100), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'PRESTADO', 'NO_DISPONIBLE', name='estadoejemplar'), nullable=True),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('libros_categorias',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'categoria_id')
    )
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_prestamo', sa.Date(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ejemplar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ejemplar_id'], ['ejemplares.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamos')
    op.drop_table('libros_categorias')
    op.drop_table('ejemplares')
    # ### end Alembic commands ###
